### ISSUE TITLE
[bug]: theme toggler not working?

### ISSUE THREAD

**Issue by jsjoeio** [ChristopherBiscardi/christopherbiscardi.github.com#109]
I was going to DM you on Twitter but figured this would probably be better.

Went to find this blog post on [Styles and Naming](https://www.christopherbiscardi.com/post/styles-and-naming/) to share with a coworker and noticed the theme toggler wasn't working 😢 Thought you'd want to know.

![2019-12-12 10 47 45](https://user-images.githubusercontent.com/3806031/70736180-feaedc00-1ccc-11ea-8045-515ea5f67e91.gif)

**Comment by ChristopherBiscardi** [comment]
Thanks for letting me know! I, uh, intentionally broke it and then forgot to remove it 🙃 

I'm building a tool for writing blog posts and such and as part of that I'll be shipping a new site that sources from that place. Will leave this issue open until I fix it, thanks :)

**Comment by jsjoeio** [comment]
😂

> I'm building a tool for writing blog posts and such and as part of that I'll be shipping a new site that sources from that place

Sweet! Can't wait to see that 😄

**Comment by ChristopherBiscardi** [comment]
I shipped the new site :)
