### ISSUE TITLE
Jimp.hash instead of rev-hash

### ISSUE THREAD

**Issue by CanRau** [ChristopherBiscardi/christopherbiscardi.github.com#111]
I think you could use [img.hash()](https://www.learnwithjason.dev/blog/design-social-sharing-card/) instead of the extra `Buffer` and `rev-hash` I think.
https://github.com/ChristopherBiscardi/christopherbiscardi.github.com/blob/356779bebd6f2ce7d880070726d7869c1555515d/www/plugins/gatsby-plugin-og-image/index.js#L17

Maybe it's doing sthg I'm not aware of tho 🤔

**Comment by ChristopherBiscardi** [comment]
you're probably right (Thanks!!!) but I also don't use this plugin anymore, and I just rewrote my site to not use gatsby any more so this isn't relevant as of whenever I deploy the new site this week.

Thanks though!
