### ISSUE TITLE
Weird rendering of heading "w"

### ISSUE THREAD

**Issue by bickmark** [ChristopherBiscardi/christopherbiscardi.github.com#117]
<img width="169" alt="Screen Shot 2020-03-27 at 12 27 21 PM" src="https://user-images.githubusercontent.com/25678713/77792965-86bfb400-7026-11ea-96be-99cf1f525f9d.png">
<img width="248" alt="Screen Shot 2020-03-27 at 12 26 59 PM" src="https://user-images.githubusercontent.com/25678713/77792968-87f0e100-7026-11ea-8b26-c26abdd3c390.png">
MacOS Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by ChristopherBiscardi** [comment]
I'm using Inter Display (against recommendations) and the issue is that: https://github.com/rsms/inter/issues/244

I'll probably swap it to regular inter or system-ui in the meantime.

**Comment by ChristopherBiscardi** [comment]
New version of Inter Display fixed the w
![image](https://user-images.githubusercontent.com/551247/79057829-993b0f80-7c1a-11ea-9979-24b9c9b854aa.png)
